global_costmap:
   global_frame: /map
   robot_base_frame: /base_link
   update_frequency: 2.0  #地图更新的频率
   publish_frequency: 0.0  #地图发布出来显示更新的频率
   static_map: true
   rolling_window: false  #当静态地图设置为true，rolling_window设置为false
   resolution: 0.05
   transform_tolerance: 1.0  #指定tf变换中能容许的数据延迟的时间，这里为1s
   map_type: costmap

   plugins:
     - {name: static_layer, type: "costmap_2d::StaticLayer"}
     - {name: sonar_layer, type: "range_sensor_layer::RangeSensorLayer"}
     - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

   sonar_layer:
     topics: ["/ultra_dist1","/ultra_dist2","/ultra_dist3","/ultra_dist4","/ultra_dist5","/ultra_dist6"]
     no_reading_timeout: 1.0
     clear_threshold: 0.6
     mark_threshold: 0.8
     clear_on_max_reading: true
   
   obstacle_layer:
     enable: true
     track_unknown_space: true
     footprint_clearing_enabled: true
     combination_method: 1
     observation_sources: scan
     scan: {sensor_frame: /laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, clear_on_max_reading: true, inf_is_valid: true}

   inflation_layer:
     enable: true
     inflation_radius: 0.45
     cost_scaling_factor: 2.0
    
