// Generated by gencpp from file api_msgs/AddGoal.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_ADDGOAL_H
#define API_MSGS_MESSAGE_ADDGOAL_H

#include <ros/service_traits.h>


#include <api_msgs/AddGoalRequest.h>
#include <api_msgs/AddGoalResponse.h>


namespace api_msgs
{

struct AddGoal
{

typedef AddGoalRequest Request;
typedef AddGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddGoal
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::AddGoal > {
  static const char* value()
  {
    return "802c28d41326fad853e80597ef4c8c7f";
  }

  static const char* value(const ::api_msgs::AddGoal&) { return value(); }
};

template<>
struct DataType< ::api_msgs::AddGoal > {
  static const char* value()
  {
    return "api_msgs/AddGoal";
  }

  static const char* value(const ::api_msgs::AddGoal&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::AddGoalRequest> should match 
// service_traits::MD5Sum< ::api_msgs::AddGoal > 
template<>
struct MD5Sum< ::api_msgs::AddGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::AddGoal >::value();
  }
  static const char* value(const ::api_msgs::AddGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::AddGoalRequest> should match 
// service_traits::DataType< ::api_msgs::AddGoal > 
template<>
struct DataType< ::api_msgs::AddGoalRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::AddGoal >::value();
  }
  static const char* value(const ::api_msgs::AddGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::AddGoalResponse> should match 
// service_traits::MD5Sum< ::api_msgs::AddGoal > 
template<>
struct MD5Sum< ::api_msgs::AddGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::AddGoal >::value();
  }
  static const char* value(const ::api_msgs::AddGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::AddGoalResponse> should match 
// service_traits::DataType< ::api_msgs::AddGoal > 
template<>
struct DataType< ::api_msgs::AddGoalResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::AddGoal >::value();
  }
  static const char* value(const ::api_msgs::AddGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_ADDGOAL_H
