// Generated by gencpp from file api_msgs/CustomInitialize.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_CUSTOMINITIALIZE_H
#define API_MSGS_MESSAGE_CUSTOMINITIALIZE_H

#include <ros/service_traits.h>


#include <api_msgs/CustomInitializeRequest.h>
#include <api_msgs/CustomInitializeResponse.h>


namespace api_msgs
{

struct CustomInitialize
{

typedef CustomInitializeRequest Request;
typedef CustomInitializeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CustomInitialize
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::CustomInitialize > {
  static const char* value()
  {
    return "b6a325da20ef37edfcee672b352f2968";
  }

  static const char* value(const ::api_msgs::CustomInitialize&) { return value(); }
};

template<>
struct DataType< ::api_msgs::CustomInitialize > {
  static const char* value()
  {
    return "api_msgs/CustomInitialize";
  }

  static const char* value(const ::api_msgs::CustomInitialize&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::CustomInitializeRequest> should match 
// service_traits::MD5Sum< ::api_msgs::CustomInitialize > 
template<>
struct MD5Sum< ::api_msgs::CustomInitializeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::CustomInitialize >::value();
  }
  static const char* value(const ::api_msgs::CustomInitializeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::CustomInitializeRequest> should match 
// service_traits::DataType< ::api_msgs::CustomInitialize > 
template<>
struct DataType< ::api_msgs::CustomInitializeRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::CustomInitialize >::value();
  }
  static const char* value(const ::api_msgs::CustomInitializeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::CustomInitializeResponse> should match 
// service_traits::MD5Sum< ::api_msgs::CustomInitialize > 
template<>
struct MD5Sum< ::api_msgs::CustomInitializeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::CustomInitialize >::value();
  }
  static const char* value(const ::api_msgs::CustomInitializeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::CustomInitializeResponse> should match 
// service_traits::DataType< ::api_msgs::CustomInitialize > 
template<>
struct DataType< ::api_msgs::CustomInitializeResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::CustomInitialize >::value();
  }
  static const char* value(const ::api_msgs::CustomInitializeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_CUSTOMINITIALIZE_H
