// Generated by gencpp from file api_msgs/CustomMove.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_CUSTOMMOVE_H
#define API_MSGS_MESSAGE_CUSTOMMOVE_H

#include <ros/service_traits.h>


#include <api_msgs/CustomMoveRequest.h>
#include <api_msgs/CustomMoveResponse.h>


namespace api_msgs
{

struct CustomMove
{

typedef CustomMoveRequest Request;
typedef CustomMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CustomMove
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::CustomMove > {
  static const char* value()
  {
    return "7af0037f1549a52fbb4460febba2b5c4";
  }

  static const char* value(const ::api_msgs::CustomMove&) { return value(); }
};

template<>
struct DataType< ::api_msgs::CustomMove > {
  static const char* value()
  {
    return "api_msgs/CustomMove";
  }

  static const char* value(const ::api_msgs::CustomMove&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::CustomMoveRequest> should match 
// service_traits::MD5Sum< ::api_msgs::CustomMove > 
template<>
struct MD5Sum< ::api_msgs::CustomMoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::CustomMove >::value();
  }
  static const char* value(const ::api_msgs::CustomMoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::CustomMoveRequest> should match 
// service_traits::DataType< ::api_msgs::CustomMove > 
template<>
struct DataType< ::api_msgs::CustomMoveRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::CustomMove >::value();
  }
  static const char* value(const ::api_msgs::CustomMoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::CustomMoveResponse> should match 
// service_traits::MD5Sum< ::api_msgs::CustomMove > 
template<>
struct MD5Sum< ::api_msgs::CustomMoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::CustomMove >::value();
  }
  static const char* value(const ::api_msgs::CustomMoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::CustomMoveResponse> should match 
// service_traits::DataType< ::api_msgs::CustomMove > 
template<>
struct DataType< ::api_msgs::CustomMoveResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::CustomMove >::value();
  }
  static const char* value(const ::api_msgs::CustomMoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_CUSTOMMOVE_H
