// Generated by gencpp from file api_msgs/DelGoal.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_DELGOAL_H
#define API_MSGS_MESSAGE_DELGOAL_H

#include <ros/service_traits.h>


#include <api_msgs/DelGoalRequest.h>
#include <api_msgs/DelGoalResponse.h>


namespace api_msgs
{

struct DelGoal
{

typedef DelGoalRequest Request;
typedef DelGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DelGoal
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::DelGoal > {
  static const char* value()
  {
    return "7ed70b59a7bfaaa4a886dd445668c789";
  }

  static const char* value(const ::api_msgs::DelGoal&) { return value(); }
};

template<>
struct DataType< ::api_msgs::DelGoal > {
  static const char* value()
  {
    return "api_msgs/DelGoal";
  }

  static const char* value(const ::api_msgs::DelGoal&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::DelGoalRequest> should match 
// service_traits::MD5Sum< ::api_msgs::DelGoal > 
template<>
struct MD5Sum< ::api_msgs::DelGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::DelGoal >::value();
  }
  static const char* value(const ::api_msgs::DelGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::DelGoalRequest> should match 
// service_traits::DataType< ::api_msgs::DelGoal > 
template<>
struct DataType< ::api_msgs::DelGoalRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::DelGoal >::value();
  }
  static const char* value(const ::api_msgs::DelGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::DelGoalResponse> should match 
// service_traits::MD5Sum< ::api_msgs::DelGoal > 
template<>
struct MD5Sum< ::api_msgs::DelGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::DelGoal >::value();
  }
  static const char* value(const ::api_msgs::DelGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::DelGoalResponse> should match 
// service_traits::DataType< ::api_msgs::DelGoal > 
template<>
struct DataType< ::api_msgs::DelGoalResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::DelGoal >::value();
  }
  static const char* value(const ::api_msgs::DelGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_DELGOAL_H
