// Generated by gencpp from file api_msgs/DownloadFileResponse.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_DOWNLOADFILERESPONSE_H
#define API_MSGS_MESSAGE_DOWNLOADFILERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace api_msgs
{
template <class ContainerAllocator>
struct DownloadFileResponse_
{
  typedef DownloadFileResponse_<ContainerAllocator> Type;

  DownloadFileResponse_()
    : size(0)
    , data()
    , msg()  {
    }
  DownloadFileResponse_(const ContainerAllocator& _alloc)
    : size(0)
    , data(_alloc)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _size_type;
  _size_type size;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;




  typedef boost::shared_ptr< ::api_msgs::DownloadFileResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::api_msgs::DownloadFileResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DownloadFileResponse_

typedef ::api_msgs::DownloadFileResponse_<std::allocator<void> > DownloadFileResponse;

typedef boost::shared_ptr< ::api_msgs::DownloadFileResponse > DownloadFileResponsePtr;
typedef boost::shared_ptr< ::api_msgs::DownloadFileResponse const> DownloadFileResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::api_msgs::DownloadFileResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::api_msgs::DownloadFileResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace api_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'api_msgs': ['/home/whj/catkin_ws/src/api/api_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::api_msgs::DownloadFileResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api_msgs::DownloadFileResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api_msgs::DownloadFileResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api_msgs::DownloadFileResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api_msgs::DownloadFileResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api_msgs::DownloadFileResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::api_msgs::DownloadFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1785d1eb098ddacbf890a2474cd9b294";
  }

  static const char* value(const ::api_msgs::DownloadFileResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1785d1eb098ddacbULL;
  static const uint64_t static_value2 = 0xf890a2474cd9b294ULL;
};

template<class ContainerAllocator>
struct DataType< ::api_msgs::DownloadFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "api_msgs/DownloadFileResponse";
  }

  static const char* value(const ::api_msgs::DownloadFileResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::api_msgs::DownloadFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 size\n\
string data\n\
string msg\n\
\n\
";
  }

  static const char* value(const ::api_msgs::DownloadFileResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::api_msgs::DownloadFileResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.size);
      stream.next(m.data);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DownloadFileResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::api_msgs::DownloadFileResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::api_msgs::DownloadFileResponse_<ContainerAllocator>& v)
  {
    s << indent << "size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.size);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // API_MSGS_MESSAGE_DOWNLOADFILERESPONSE_H
