// Generated by gencpp from file api_msgs/DownloadFile.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_DOWNLOADFILE_H
#define API_MSGS_MESSAGE_DOWNLOADFILE_H

#include <ros/service_traits.h>


#include <api_msgs/DownloadFileRequest.h>
#include <api_msgs/DownloadFileResponse.h>


namespace api_msgs
{

struct DownloadFile
{

typedef DownloadFileRequest Request;
typedef DownloadFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DownloadFile
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::DownloadFile > {
  static const char* value()
  {
    return "a93515b901dc74b0c77f07911f2857ac";
  }

  static const char* value(const ::api_msgs::DownloadFile&) { return value(); }
};

template<>
struct DataType< ::api_msgs::DownloadFile > {
  static const char* value()
  {
    return "api_msgs/DownloadFile";
  }

  static const char* value(const ::api_msgs::DownloadFile&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::DownloadFileRequest> should match 
// service_traits::MD5Sum< ::api_msgs::DownloadFile > 
template<>
struct MD5Sum< ::api_msgs::DownloadFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::DownloadFile >::value();
  }
  static const char* value(const ::api_msgs::DownloadFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::DownloadFileRequest> should match 
// service_traits::DataType< ::api_msgs::DownloadFile > 
template<>
struct DataType< ::api_msgs::DownloadFileRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::DownloadFile >::value();
  }
  static const char* value(const ::api_msgs::DownloadFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::DownloadFileResponse> should match 
// service_traits::MD5Sum< ::api_msgs::DownloadFile > 
template<>
struct MD5Sum< ::api_msgs::DownloadFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::DownloadFile >::value();
  }
  static const char* value(const ::api_msgs::DownloadFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::DownloadFileResponse> should match 
// service_traits::DataType< ::api_msgs::DownloadFile > 
template<>
struct DataType< ::api_msgs::DownloadFileResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::DownloadFile >::value();
  }
  static const char* value(const ::api_msgs::DownloadFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_DOWNLOADFILE_H
