// Generated by gencpp from file api_msgs/DownloadMap.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_DOWNLOADMAP_H
#define API_MSGS_MESSAGE_DOWNLOADMAP_H

#include <ros/service_traits.h>


#include <api_msgs/DownloadMapRequest.h>
#include <api_msgs/DownloadMapResponse.h>


namespace api_msgs
{

struct DownloadMap
{

typedef DownloadMapRequest Request;
typedef DownloadMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DownloadMap
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::DownloadMap > {
  static const char* value()
  {
    return "2baa25a9186e1f428009e476983334ce";
  }

  static const char* value(const ::api_msgs::DownloadMap&) { return value(); }
};

template<>
struct DataType< ::api_msgs::DownloadMap > {
  static const char* value()
  {
    return "api_msgs/DownloadMap";
  }

  static const char* value(const ::api_msgs::DownloadMap&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::DownloadMapRequest> should match 
// service_traits::MD5Sum< ::api_msgs::DownloadMap > 
template<>
struct MD5Sum< ::api_msgs::DownloadMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::DownloadMap >::value();
  }
  static const char* value(const ::api_msgs::DownloadMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::DownloadMapRequest> should match 
// service_traits::DataType< ::api_msgs::DownloadMap > 
template<>
struct DataType< ::api_msgs::DownloadMapRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::DownloadMap >::value();
  }
  static const char* value(const ::api_msgs::DownloadMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::DownloadMapResponse> should match 
// service_traits::MD5Sum< ::api_msgs::DownloadMap > 
template<>
struct MD5Sum< ::api_msgs::DownloadMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::DownloadMap >::value();
  }
  static const char* value(const ::api_msgs::DownloadMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::DownloadMapResponse> should match 
// service_traits::DataType< ::api_msgs::DownloadMap > 
template<>
struct DataType< ::api_msgs::DownloadMapResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::DownloadMap >::value();
  }
  static const char* value(const ::api_msgs::DownloadMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_DOWNLOADMAP_H
