// Generated by gencpp from file api_msgs/GetFile.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_GETFILE_H
#define API_MSGS_MESSAGE_GETFILE_H

#include <ros/service_traits.h>


#include <api_msgs/GetFileRequest.h>
#include <api_msgs/GetFileResponse.h>


namespace api_msgs
{

struct GetFile
{

typedef GetFileRequest Request;
typedef GetFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFile
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::GetFile > {
  static const char* value()
  {
    return "b6f4d556a4d514eccc6afa6e8d44d8f9";
  }

  static const char* value(const ::api_msgs::GetFile&) { return value(); }
};

template<>
struct DataType< ::api_msgs::GetFile > {
  static const char* value()
  {
    return "api_msgs/GetFile";
  }

  static const char* value(const ::api_msgs::GetFile&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::GetFileRequest> should match 
// service_traits::MD5Sum< ::api_msgs::GetFile > 
template<>
struct MD5Sum< ::api_msgs::GetFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::GetFile >::value();
  }
  static const char* value(const ::api_msgs::GetFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::GetFileRequest> should match 
// service_traits::DataType< ::api_msgs::GetFile > 
template<>
struct DataType< ::api_msgs::GetFileRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::GetFile >::value();
  }
  static const char* value(const ::api_msgs::GetFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::GetFileResponse> should match 
// service_traits::MD5Sum< ::api_msgs::GetFile > 
template<>
struct MD5Sum< ::api_msgs::GetFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::GetFile >::value();
  }
  static const char* value(const ::api_msgs::GetFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::GetFileResponse> should match 
// service_traits::DataType< ::api_msgs::GetFile > 
template<>
struct DataType< ::api_msgs::GetFileResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::GetFile >::value();
  }
  static const char* value(const ::api_msgs::GetFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_GETFILE_H
