// Generated by gencpp from file api_msgs/GetList.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_GETLIST_H
#define API_MSGS_MESSAGE_GETLIST_H

#include <ros/service_traits.h>


#include <api_msgs/GetListRequest.h>
#include <api_msgs/GetListResponse.h>


namespace api_msgs
{

struct GetList
{

typedef GetListRequest Request;
typedef GetListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetList
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::GetList > {
  static const char* value()
  {
    return "2a8a9dfc6e6eb932884b5893f306dd1b";
  }

  static const char* value(const ::api_msgs::GetList&) { return value(); }
};

template<>
struct DataType< ::api_msgs::GetList > {
  static const char* value()
  {
    return "api_msgs/GetList";
  }

  static const char* value(const ::api_msgs::GetList&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::GetListRequest> should match 
// service_traits::MD5Sum< ::api_msgs::GetList > 
template<>
struct MD5Sum< ::api_msgs::GetListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::GetList >::value();
  }
  static const char* value(const ::api_msgs::GetListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::GetListRequest> should match 
// service_traits::DataType< ::api_msgs::GetList > 
template<>
struct DataType< ::api_msgs::GetListRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::GetList >::value();
  }
  static const char* value(const ::api_msgs::GetListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::GetListResponse> should match 
// service_traits::MD5Sum< ::api_msgs::GetList > 
template<>
struct MD5Sum< ::api_msgs::GetListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::GetList >::value();
  }
  static const char* value(const ::api_msgs::GetListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::GetListResponse> should match 
// service_traits::DataType< ::api_msgs::GetList > 
template<>
struct DataType< ::api_msgs::GetListResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::GetList >::value();
  }
  static const char* value(const ::api_msgs::GetListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_GETLIST_H
