// Generated by gencpp from file api_msgs/GoalList.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_GOALLIST_H
#define API_MSGS_MESSAGE_GOALLIST_H

#include <ros/service_traits.h>


#include <api_msgs/GoalListRequest.h>
#include <api_msgs/GoalListResponse.h>


namespace api_msgs
{

struct GoalList
{

typedef GoalListRequest Request;
typedef GoalListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoalList
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::GoalList > {
  static const char* value()
  {
    return "6ded0e823bc3364a8e51670166f50c09";
  }

  static const char* value(const ::api_msgs::GoalList&) { return value(); }
};

template<>
struct DataType< ::api_msgs::GoalList > {
  static const char* value()
  {
    return "api_msgs/GoalList";
  }

  static const char* value(const ::api_msgs::GoalList&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::GoalListRequest> should match 
// service_traits::MD5Sum< ::api_msgs::GoalList > 
template<>
struct MD5Sum< ::api_msgs::GoalListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::GoalList >::value();
  }
  static const char* value(const ::api_msgs::GoalListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::GoalListRequest> should match 
// service_traits::DataType< ::api_msgs::GoalList > 
template<>
struct DataType< ::api_msgs::GoalListRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::GoalList >::value();
  }
  static const char* value(const ::api_msgs::GoalListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::GoalListResponse> should match 
// service_traits::MD5Sum< ::api_msgs::GoalList > 
template<>
struct MD5Sum< ::api_msgs::GoalListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::GoalList >::value();
  }
  static const char* value(const ::api_msgs::GoalListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::GoalListResponse> should match 
// service_traits::DataType< ::api_msgs::GoalList > 
template<>
struct DataType< ::api_msgs::GoalListResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::GoalList >::value();
  }
  static const char* value(const ::api_msgs::GoalListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_GOALLIST_H
