// Generated by gencpp from file api_msgs/GridPoseResponse.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_GRIDPOSERESPONSE_H
#define API_MSGS_MESSAGE_GRIDPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <api_msgs/GridPoint.h>
#include <api_msgs/GridPoint.h>

namespace api_msgs
{
template <class ContainerAllocator>
struct GridPoseResponse_
{
  typedef GridPoseResponse_<ContainerAllocator> Type;

  GridPoseResponse_()
    : pose()
    , head()
    , msg()  {
    }
  GridPoseResponse_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , head(_alloc)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef  ::api_msgs::GridPoint_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::api_msgs::GridPoint_<ContainerAllocator>  _head_type;
  _head_type head;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;




  typedef boost::shared_ptr< ::api_msgs::GridPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::api_msgs::GridPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GridPoseResponse_

typedef ::api_msgs::GridPoseResponse_<std::allocator<void> > GridPoseResponse;

typedef boost::shared_ptr< ::api_msgs::GridPoseResponse > GridPoseResponsePtr;
typedef boost::shared_ptr< ::api_msgs::GridPoseResponse const> GridPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::api_msgs::GridPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::api_msgs::GridPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace api_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'api_msgs': ['/home/whj/catkin_ws/src/api/api_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::api_msgs::GridPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api_msgs::GridPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api_msgs::GridPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api_msgs::GridPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api_msgs::GridPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api_msgs::GridPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::api_msgs::GridPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "325a9b2e47d12334233bcc0412c03a62";
  }

  static const char* value(const ::api_msgs::GridPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x325a9b2e47d12334ULL;
  static const uint64_t static_value2 = 0x233bcc0412c03a62ULL;
};

template<class ContainerAllocator>
struct DataType< ::api_msgs::GridPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "api_msgs/GridPoseResponse";
  }

  static const char* value(const ::api_msgs::GridPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::api_msgs::GridPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "GridPoint pose\n\
GridPoint head\n\
string  msg\n\
\n\
\n\
================================================================================\n\
MSG: api_msgs/GridPoint\n\
int32 x\n\
int32 y\n\
";
  }

  static const char* value(const ::api_msgs::GridPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::api_msgs::GridPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.head);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GridPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::api_msgs::GridPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::api_msgs::GridPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::api_msgs::GridPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "head: ";
    s << std::endl;
    Printer< ::api_msgs::GridPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.head);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // API_MSGS_MESSAGE_GRIDPOSERESPONSE_H
