// Generated by gencpp from file api_msgs/GridLaser.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_GRIDLASER_H
#define API_MSGS_MESSAGE_GRIDLASER_H

#include <ros/service_traits.h>


#include <api_msgs/GridLaserRequest.h>
#include <api_msgs/GridLaserResponse.h>


namespace api_msgs
{

struct GridLaser
{

typedef GridLaserRequest Request;
typedef GridLaserResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GridLaser
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::GridLaser > {
  static const char* value()
  {
    return "70385a002e518c7e14ab0566622593e3";
  }

  static const char* value(const ::api_msgs::GridLaser&) { return value(); }
};

template<>
struct DataType< ::api_msgs::GridLaser > {
  static const char* value()
  {
    return "api_msgs/GridLaser";
  }

  static const char* value(const ::api_msgs::GridLaser&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::GridLaserRequest> should match 
// service_traits::MD5Sum< ::api_msgs::GridLaser > 
template<>
struct MD5Sum< ::api_msgs::GridLaserRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::GridLaser >::value();
  }
  static const char* value(const ::api_msgs::GridLaserRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::GridLaserRequest> should match 
// service_traits::DataType< ::api_msgs::GridLaser > 
template<>
struct DataType< ::api_msgs::GridLaserRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::GridLaser >::value();
  }
  static const char* value(const ::api_msgs::GridLaserRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::GridLaserResponse> should match 
// service_traits::MD5Sum< ::api_msgs::GridLaser > 
template<>
struct MD5Sum< ::api_msgs::GridLaserResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::GridLaser >::value();
  }
  static const char* value(const ::api_msgs::GridLaserResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::GridLaserResponse> should match 
// service_traits::DataType< ::api_msgs::GridLaser > 
template<>
struct DataType< ::api_msgs::GridLaserResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::GridLaser >::value();
  }
  static const char* value(const ::api_msgs::GridLaserResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_GRIDLASER_H
