// Generated by gencpp from file api_msgs/GridSonar.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_GRIDSONAR_H
#define API_MSGS_MESSAGE_GRIDSONAR_H

#include <ros/service_traits.h>


#include <api_msgs/GridSonarRequest.h>
#include <api_msgs/GridSonarResponse.h>


namespace api_msgs
{

struct GridSonar
{

typedef GridSonarRequest Request;
typedef GridSonarResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GridSonar
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::GridSonar > {
  static const char* value()
  {
    return "669b7318ba1fac1b95da7f086bcce00d";
  }

  static const char* value(const ::api_msgs::GridSonar&) { return value(); }
};

template<>
struct DataType< ::api_msgs::GridSonar > {
  static const char* value()
  {
    return "api_msgs/GridSonar";
  }

  static const char* value(const ::api_msgs::GridSonar&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::GridSonarRequest> should match 
// service_traits::MD5Sum< ::api_msgs::GridSonar > 
template<>
struct MD5Sum< ::api_msgs::GridSonarRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::GridSonar >::value();
  }
  static const char* value(const ::api_msgs::GridSonarRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::GridSonarRequest> should match 
// service_traits::DataType< ::api_msgs::GridSonar > 
template<>
struct DataType< ::api_msgs::GridSonarRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::GridSonar >::value();
  }
  static const char* value(const ::api_msgs::GridSonarRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::GridSonarResponse> should match 
// service_traits::MD5Sum< ::api_msgs::GridSonar > 
template<>
struct MD5Sum< ::api_msgs::GridSonarResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::GridSonar >::value();
  }
  static const char* value(const ::api_msgs::GridSonarResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::GridSonarResponse> should match 
// service_traits::DataType< ::api_msgs::GridSonar > 
template<>
struct DataType< ::api_msgs::GridSonarResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::GridSonar >::value();
  }
  static const char* value(const ::api_msgs::GridSonarResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_GRIDSONAR_H
