// Generated by gencpp from file api_msgs/GridPose.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_GRIDPOSE_H
#define API_MSGS_MESSAGE_GRIDPOSE_H

#include <ros/service_traits.h>


#include <api_msgs/GridPoseRequest.h>
#include <api_msgs/GridPoseResponse.h>


namespace api_msgs
{

struct GridPose
{

typedef GridPoseRequest Request;
typedef GridPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GridPose
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::GridPose > {
  static const char* value()
  {
    return "cb86799e520e4383cc93ac173628b1c6";
  }

  static const char* value(const ::api_msgs::GridPose&) { return value(); }
};

template<>
struct DataType< ::api_msgs::GridPose > {
  static const char* value()
  {
    return "api_msgs/GridPose";
  }

  static const char* value(const ::api_msgs::GridPose&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::GridPoseRequest> should match 
// service_traits::MD5Sum< ::api_msgs::GridPose > 
template<>
struct MD5Sum< ::api_msgs::GridPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::GridPose >::value();
  }
  static const char* value(const ::api_msgs::GridPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::GridPoseRequest> should match 
// service_traits::DataType< ::api_msgs::GridPose > 
template<>
struct DataType< ::api_msgs::GridPoseRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::GridPose >::value();
  }
  static const char* value(const ::api_msgs::GridPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::GridPoseResponse> should match 
// service_traits::MD5Sum< ::api_msgs::GridPose > 
template<>
struct MD5Sum< ::api_msgs::GridPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::GridPose >::value();
  }
  static const char* value(const ::api_msgs::GridPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::GridPoseResponse> should match 
// service_traits::DataType< ::api_msgs::GridPose > 
template<>
struct DataType< ::api_msgs::GridPoseResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::GridPose >::value();
  }
  static const char* value(const ::api_msgs::GridPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_GRIDPOSE_H
