// Generated by gencpp from file api_msgs/MapList.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_MAPLIST_H
#define API_MSGS_MESSAGE_MAPLIST_H

#include <ros/service_traits.h>


#include <api_msgs/MapListRequest.h>
#include <api_msgs/MapListResponse.h>


namespace api_msgs
{

struct MapList
{

typedef MapListRequest Request;
typedef MapListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapList
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::MapList > {
  static const char* value()
  {
    return "68d5e7574159c309cadccc1b40fe9cc1";
  }

  static const char* value(const ::api_msgs::MapList&) { return value(); }
};

template<>
struct DataType< ::api_msgs::MapList > {
  static const char* value()
  {
    return "api_msgs/MapList";
  }

  static const char* value(const ::api_msgs::MapList&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::MapListRequest> should match 
// service_traits::MD5Sum< ::api_msgs::MapList > 
template<>
struct MD5Sum< ::api_msgs::MapListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::MapList >::value();
  }
  static const char* value(const ::api_msgs::MapListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::MapListRequest> should match 
// service_traits::DataType< ::api_msgs::MapList > 
template<>
struct DataType< ::api_msgs::MapListRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::MapList >::value();
  }
  static const char* value(const ::api_msgs::MapListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::MapListResponse> should match 
// service_traits::MD5Sum< ::api_msgs::MapList > 
template<>
struct MD5Sum< ::api_msgs::MapListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::MapList >::value();
  }
  static const char* value(const ::api_msgs::MapListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::MapListResponse> should match 
// service_traits::DataType< ::api_msgs::MapList > 
template<>
struct DataType< ::api_msgs::MapListResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::MapList >::value();
  }
  static const char* value(const ::api_msgs::MapListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_MAPLIST_H
