// Generated by gencpp from file api_msgs/MapRename.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_MAPRENAME_H
#define API_MSGS_MESSAGE_MAPRENAME_H

#include <ros/service_traits.h>


#include <api_msgs/MapRenameRequest.h>
#include <api_msgs/MapRenameResponse.h>


namespace api_msgs
{

struct MapRename
{

typedef MapRenameRequest Request;
typedef MapRenameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapRename
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::MapRename > {
  static const char* value()
  {
    return "12d2a39948ea8253e5f441c3a0f822dc";
  }

  static const char* value(const ::api_msgs::MapRename&) { return value(); }
};

template<>
struct DataType< ::api_msgs::MapRename > {
  static const char* value()
  {
    return "api_msgs/MapRename";
  }

  static const char* value(const ::api_msgs::MapRename&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::MapRenameRequest> should match 
// service_traits::MD5Sum< ::api_msgs::MapRename > 
template<>
struct MD5Sum< ::api_msgs::MapRenameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::MapRename >::value();
  }
  static const char* value(const ::api_msgs::MapRenameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::MapRenameRequest> should match 
// service_traits::DataType< ::api_msgs::MapRename > 
template<>
struct DataType< ::api_msgs::MapRenameRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::MapRename >::value();
  }
  static const char* value(const ::api_msgs::MapRenameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::MapRenameResponse> should match 
// service_traits::MD5Sum< ::api_msgs::MapRename > 
template<>
struct MD5Sum< ::api_msgs::MapRenameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::MapRename >::value();
  }
  static const char* value(const ::api_msgs::MapRenameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::MapRenameResponse> should match 
// service_traits::DataType< ::api_msgs::MapRename > 
template<>
struct DataType< ::api_msgs::MapRenameResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::MapRename >::value();
  }
  static const char* value(const ::api_msgs::MapRenameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_MAPRENAME_H
