// Generated by gencpp from file api_msgs/NavGoal.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_NAVGOAL_H
#define API_MSGS_MESSAGE_NAVGOAL_H

#include <ros/service_traits.h>


#include <api_msgs/NavGoalRequest.h>
#include <api_msgs/NavGoalResponse.h>


namespace api_msgs
{

struct NavGoal
{

typedef NavGoalRequest Request;
typedef NavGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavGoal
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::NavGoal > {
  static const char* value()
  {
    return "7ed70b59a7bfaaa4a886dd445668c789";
  }

  static const char* value(const ::api_msgs::NavGoal&) { return value(); }
};

template<>
struct DataType< ::api_msgs::NavGoal > {
  static const char* value()
  {
    return "api_msgs/NavGoal";
  }

  static const char* value(const ::api_msgs::NavGoal&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::NavGoalRequest> should match 
// service_traits::MD5Sum< ::api_msgs::NavGoal > 
template<>
struct MD5Sum< ::api_msgs::NavGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::NavGoal >::value();
  }
  static const char* value(const ::api_msgs::NavGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::NavGoalRequest> should match 
// service_traits::DataType< ::api_msgs::NavGoal > 
template<>
struct DataType< ::api_msgs::NavGoalRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::NavGoal >::value();
  }
  static const char* value(const ::api_msgs::NavGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::NavGoalResponse> should match 
// service_traits::MD5Sum< ::api_msgs::NavGoal > 
template<>
struct MD5Sum< ::api_msgs::NavGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::NavGoal >::value();
  }
  static const char* value(const ::api_msgs::NavGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::NavGoalResponse> should match 
// service_traits::DataType< ::api_msgs::NavGoal > 
template<>
struct DataType< ::api_msgs::NavGoalResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::NavGoal >::value();
  }
  static const char* value(const ::api_msgs::NavGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_NAVGOAL_H
