// Generated by gencpp from file api_msgs/NavToGoal.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_NAVTOGOAL_H
#define API_MSGS_MESSAGE_NAVTOGOAL_H

#include <ros/service_traits.h>


#include <api_msgs/NavToGoalRequest.h>
#include <api_msgs/NavToGoalResponse.h>


namespace api_msgs
{

struct NavToGoal
{

typedef NavToGoalRequest Request;
typedef NavToGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavToGoal
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::NavToGoal > {
  static const char* value()
  {
    return "7ed70b59a7bfaaa4a886dd445668c789";
  }

  static const char* value(const ::api_msgs::NavToGoal&) { return value(); }
};

template<>
struct DataType< ::api_msgs::NavToGoal > {
  static const char* value()
  {
    return "api_msgs/NavToGoal";
  }

  static const char* value(const ::api_msgs::NavToGoal&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::NavToGoalRequest> should match 
// service_traits::MD5Sum< ::api_msgs::NavToGoal > 
template<>
struct MD5Sum< ::api_msgs::NavToGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::NavToGoal >::value();
  }
  static const char* value(const ::api_msgs::NavToGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::NavToGoalRequest> should match 
// service_traits::DataType< ::api_msgs::NavToGoal > 
template<>
struct DataType< ::api_msgs::NavToGoalRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::NavToGoal >::value();
  }
  static const char* value(const ::api_msgs::NavToGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::NavToGoalResponse> should match 
// service_traits::MD5Sum< ::api_msgs::NavToGoal > 
template<>
struct MD5Sum< ::api_msgs::NavToGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::NavToGoal >::value();
  }
  static const char* value(const ::api_msgs::NavToGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::NavToGoalResponse> should match 
// service_traits::DataType< ::api_msgs::NavToGoal > 
template<>
struct DataType< ::api_msgs::NavToGoalResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::NavToGoal >::value();
  }
  static const char* value(const ::api_msgs::NavToGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_NAVTOGOAL_H
