// Generated by gencpp from file api_msgs/NavToGoalRequest.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_NAVTOGOALREQUEST_H
#define API_MSGS_MESSAGE_NAVTOGOALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace api_msgs
{
template <class ContainerAllocator>
struct NavToGoalRequest_
{
  typedef NavToGoalRequest_<ContainerAllocator> Type;

  NavToGoalRequest_()
    : mapName()
    , goalName()  {
    }
  NavToGoalRequest_(const ContainerAllocator& _alloc)
    : mapName(_alloc)
    , goalName(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mapName_type;
  _mapName_type mapName;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _goalName_type;
  _goalName_type goalName;




  typedef boost::shared_ptr< ::api_msgs::NavToGoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::api_msgs::NavToGoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NavToGoalRequest_

typedef ::api_msgs::NavToGoalRequest_<std::allocator<void> > NavToGoalRequest;

typedef boost::shared_ptr< ::api_msgs::NavToGoalRequest > NavToGoalRequestPtr;
typedef boost::shared_ptr< ::api_msgs::NavToGoalRequest const> NavToGoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::api_msgs::NavToGoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::api_msgs::NavToGoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace api_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'api_msgs': ['/home/whj/catkin_ws/src/api/api_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::api_msgs::NavToGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api_msgs::NavToGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api_msgs::NavToGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api_msgs::NavToGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api_msgs::NavToGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api_msgs::NavToGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::api_msgs::NavToGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2b7bd197c8eeb3abbefa402ec01e6fe";
  }

  static const char* value(const ::api_msgs::NavToGoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2b7bd197c8eeb3aULL;
  static const uint64_t static_value2 = 0xbbefa402ec01e6feULL;
};

template<class ContainerAllocator>
struct DataType< ::api_msgs::NavToGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "api_msgs/NavToGoalRequest";
  }

  static const char* value(const ::api_msgs::NavToGoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::api_msgs::NavToGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mapName\n\
string goalName\n\
";
  }

  static const char* value(const ::api_msgs::NavToGoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::api_msgs::NavToGoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapName);
      stream.next(m.goalName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavToGoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::api_msgs::NavToGoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::api_msgs::NavToGoalRequest_<ContainerAllocator>& v)
  {
    s << indent << "mapName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mapName);
    s << indent << "goalName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.goalName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // API_MSGS_MESSAGE_NAVTOGOALREQUEST_H
