// Generated by gencpp from file api_msgs/PredefinedInitialize.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_PREDEFINEDINITIALIZE_H
#define API_MSGS_MESSAGE_PREDEFINEDINITIALIZE_H

#include <ros/service_traits.h>


#include <api_msgs/PredefinedInitializeRequest.h>
#include <api_msgs/PredefinedInitializeResponse.h>


namespace api_msgs
{

struct PredefinedInitialize
{

typedef PredefinedInitializeRequest Request;
typedef PredefinedInitializeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PredefinedInitialize
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::PredefinedInitialize > {
  static const char* value()
  {
    return "7ed70b59a7bfaaa4a886dd445668c789";
  }

  static const char* value(const ::api_msgs::PredefinedInitialize&) { return value(); }
};

template<>
struct DataType< ::api_msgs::PredefinedInitialize > {
  static const char* value()
  {
    return "api_msgs/PredefinedInitialize";
  }

  static const char* value(const ::api_msgs::PredefinedInitialize&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::PredefinedInitializeRequest> should match 
// service_traits::MD5Sum< ::api_msgs::PredefinedInitialize > 
template<>
struct MD5Sum< ::api_msgs::PredefinedInitializeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::PredefinedInitialize >::value();
  }
  static const char* value(const ::api_msgs::PredefinedInitializeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::PredefinedInitializeRequest> should match 
// service_traits::DataType< ::api_msgs::PredefinedInitialize > 
template<>
struct DataType< ::api_msgs::PredefinedInitializeRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::PredefinedInitialize >::value();
  }
  static const char* value(const ::api_msgs::PredefinedInitializeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::PredefinedInitializeResponse> should match 
// service_traits::MD5Sum< ::api_msgs::PredefinedInitialize > 
template<>
struct MD5Sum< ::api_msgs::PredefinedInitializeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::PredefinedInitialize >::value();
  }
  static const char* value(const ::api_msgs::PredefinedInitializeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::PredefinedInitializeResponse> should match 
// service_traits::DataType< ::api_msgs::PredefinedInitialize > 
template<>
struct DataType< ::api_msgs::PredefinedInitializeResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::PredefinedInitialize >::value();
  }
  static const char* value(const ::api_msgs::PredefinedInitializeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_PREDEFINEDINITIALIZE_H
