// Generated by gencpp from file api_msgs/PushMapResponse.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_PUSHMAPRESPONSE_H
#define API_MSGS_MESSAGE_PUSHMAPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace api_msgs
{
template <class ContainerAllocator>
struct PushMapResponse_
{
  typedef PushMapResponse_<ContainerAllocator> Type;

  PushMapResponse_()
    : mapSize()
    , yamlSize()
    , msg()  {
    }
  PushMapResponse_(const ContainerAllocator& _alloc)
    : mapSize(_alloc)
    , yamlSize(_alloc)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mapSize_type;
  _mapSize_type mapSize;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _yamlSize_type;
  _yamlSize_type yamlSize;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;




  typedef boost::shared_ptr< ::api_msgs::PushMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::api_msgs::PushMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PushMapResponse_

typedef ::api_msgs::PushMapResponse_<std::allocator<void> > PushMapResponse;

typedef boost::shared_ptr< ::api_msgs::PushMapResponse > PushMapResponsePtr;
typedef boost::shared_ptr< ::api_msgs::PushMapResponse const> PushMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::api_msgs::PushMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::api_msgs::PushMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace api_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'api_msgs': ['/home/whj/catkin_ws/src/api/api_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::api_msgs::PushMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api_msgs::PushMapResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api_msgs::PushMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api_msgs::PushMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api_msgs::PushMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api_msgs::PushMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::api_msgs::PushMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd8db35d6cbe919198edbc7bbabcef03";
  }

  static const char* value(const ::api_msgs::PushMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd8db35d6cbe9191ULL;
  static const uint64_t static_value2 = 0x98edbc7bbabcef03ULL;
};

template<class ContainerAllocator>
struct DataType< ::api_msgs::PushMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "api_msgs/PushMapResponse";
  }

  static const char* value(const ::api_msgs::PushMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::api_msgs::PushMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mapSize\n\
string yamlSize\n\
string msg\n\
\n\
";
  }

  static const char* value(const ::api_msgs::PushMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::api_msgs::PushMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapSize);
      stream.next(m.yamlSize);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PushMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::api_msgs::PushMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::api_msgs::PushMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "mapSize: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mapSize);
    s << indent << "yamlSize: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.yamlSize);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // API_MSGS_MESSAGE_PUSHMAPRESPONSE_H
