// Generated by gencpp from file api_msgs/PushFile.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_PUSHFILE_H
#define API_MSGS_MESSAGE_PUSHFILE_H

#include <ros/service_traits.h>


#include <api_msgs/PushFileRequest.h>
#include <api_msgs/PushFileResponse.h>


namespace api_msgs
{

struct PushFile
{

typedef PushFileRequest Request;
typedef PushFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PushFile
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::PushFile > {
  static const char* value()
  {
    return "29f798a8e8dbbc56374b3cb476a12e27";
  }

  static const char* value(const ::api_msgs::PushFile&) { return value(); }
};

template<>
struct DataType< ::api_msgs::PushFile > {
  static const char* value()
  {
    return "api_msgs/PushFile";
  }

  static const char* value(const ::api_msgs::PushFile&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::PushFileRequest> should match 
// service_traits::MD5Sum< ::api_msgs::PushFile > 
template<>
struct MD5Sum< ::api_msgs::PushFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::PushFile >::value();
  }
  static const char* value(const ::api_msgs::PushFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::PushFileRequest> should match 
// service_traits::DataType< ::api_msgs::PushFile > 
template<>
struct DataType< ::api_msgs::PushFileRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::PushFile >::value();
  }
  static const char* value(const ::api_msgs::PushFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::PushFileResponse> should match 
// service_traits::MD5Sum< ::api_msgs::PushFile > 
template<>
struct MD5Sum< ::api_msgs::PushFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::PushFile >::value();
  }
  static const char* value(const ::api_msgs::PushFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::PushFileResponse> should match 
// service_traits::DataType< ::api_msgs::PushFile > 
template<>
struct DataType< ::api_msgs::PushFileResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::PushFile >::value();
  }
  static const char* value(const ::api_msgs::PushFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_PUSHFILE_H
