// Generated by gencpp from file api_msgs/PushMap.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_PUSHMAP_H
#define API_MSGS_MESSAGE_PUSHMAP_H

#include <ros/service_traits.h>


#include <api_msgs/PushMapRequest.h>
#include <api_msgs/PushMapResponse.h>


namespace api_msgs
{

struct PushMap
{

typedef PushMapRequest Request;
typedef PushMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PushMap
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::PushMap > {
  static const char* value()
  {
    return "cfd78f574ce6584df58e90daeaf81197";
  }

  static const char* value(const ::api_msgs::PushMap&) { return value(); }
};

template<>
struct DataType< ::api_msgs::PushMap > {
  static const char* value()
  {
    return "api_msgs/PushMap";
  }

  static const char* value(const ::api_msgs::PushMap&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::PushMapRequest> should match 
// service_traits::MD5Sum< ::api_msgs::PushMap > 
template<>
struct MD5Sum< ::api_msgs::PushMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::PushMap >::value();
  }
  static const char* value(const ::api_msgs::PushMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::PushMapRequest> should match 
// service_traits::DataType< ::api_msgs::PushMap > 
template<>
struct DataType< ::api_msgs::PushMapRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::PushMap >::value();
  }
  static const char* value(const ::api_msgs::PushMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::PushMapResponse> should match 
// service_traits::MD5Sum< ::api_msgs::PushMap > 
template<>
struct MD5Sum< ::api_msgs::PushMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::PushMap >::value();
  }
  static const char* value(const ::api_msgs::PushMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::PushMapResponse> should match 
// service_traits::DataType< ::api_msgs::PushMap > 
template<>
struct DataType< ::api_msgs::PushMapResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::PushMap >::value();
  }
  static const char* value(const ::api_msgs::PushMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_PUSHMAP_H
