// Generated by gencpp from file api_msgs/RenameGoalRequest.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_RENAMEGOALREQUEST_H
#define API_MSGS_MESSAGE_RENAMEGOALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace api_msgs
{
template <class ContainerAllocator>
struct RenameGoalRequest_
{
  typedef RenameGoalRequest_<ContainerAllocator> Type;

  RenameGoalRequest_()
    : mapName()
    , oldGoalName()
    , newGoalName()  {
    }
  RenameGoalRequest_(const ContainerAllocator& _alloc)
    : mapName(_alloc)
    , oldGoalName(_alloc)
    , newGoalName(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mapName_type;
  _mapName_type mapName;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _oldGoalName_type;
  _oldGoalName_type oldGoalName;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _newGoalName_type;
  _newGoalName_type newGoalName;




  typedef boost::shared_ptr< ::api_msgs::RenameGoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::api_msgs::RenameGoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RenameGoalRequest_

typedef ::api_msgs::RenameGoalRequest_<std::allocator<void> > RenameGoalRequest;

typedef boost::shared_ptr< ::api_msgs::RenameGoalRequest > RenameGoalRequestPtr;
typedef boost::shared_ptr< ::api_msgs::RenameGoalRequest const> RenameGoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::api_msgs::RenameGoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::api_msgs::RenameGoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace api_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'api_msgs': ['/home/whj/catkin_ws/src/api/api_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::api_msgs::RenameGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api_msgs::RenameGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api_msgs::RenameGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api_msgs::RenameGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api_msgs::RenameGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api_msgs::RenameGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::api_msgs::RenameGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1256a1d374579be3e10f27157645b752";
  }

  static const char* value(const ::api_msgs::RenameGoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1256a1d374579be3ULL;
  static const uint64_t static_value2 = 0xe10f27157645b752ULL;
};

template<class ContainerAllocator>
struct DataType< ::api_msgs::RenameGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "api_msgs/RenameGoalRequest";
  }

  static const char* value(const ::api_msgs::RenameGoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::api_msgs::RenameGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mapName\n\
string oldGoalName\n\
string newGoalName\n\
";
  }

  static const char* value(const ::api_msgs::RenameGoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::api_msgs::RenameGoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapName);
      stream.next(m.oldGoalName);
      stream.next(m.newGoalName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RenameGoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::api_msgs::RenameGoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::api_msgs::RenameGoalRequest_<ContainerAllocator>& v)
  {
    s << indent << "mapName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mapName);
    s << indent << "oldGoalName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.oldGoalName);
    s << indent << "newGoalName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.newGoalName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // API_MSGS_MESSAGE_RENAMEGOALREQUEST_H
