// Generated by gencpp from file api_msgs/RenameGoal.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_RENAMEGOAL_H
#define API_MSGS_MESSAGE_RENAMEGOAL_H

#include <ros/service_traits.h>


#include <api_msgs/RenameGoalRequest.h>
#include <api_msgs/RenameGoalResponse.h>


namespace api_msgs
{

struct RenameGoal
{

typedef RenameGoalRequest Request;
typedef RenameGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RenameGoal
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::RenameGoal > {
  static const char* value()
  {
    return "e7761fd55890403f9b95bbf9595e458d";
  }

  static const char* value(const ::api_msgs::RenameGoal&) { return value(); }
};

template<>
struct DataType< ::api_msgs::RenameGoal > {
  static const char* value()
  {
    return "api_msgs/RenameGoal";
  }

  static const char* value(const ::api_msgs::RenameGoal&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::RenameGoalRequest> should match 
// service_traits::MD5Sum< ::api_msgs::RenameGoal > 
template<>
struct MD5Sum< ::api_msgs::RenameGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::RenameGoal >::value();
  }
  static const char* value(const ::api_msgs::RenameGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::RenameGoalRequest> should match 
// service_traits::DataType< ::api_msgs::RenameGoal > 
template<>
struct DataType< ::api_msgs::RenameGoalRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::RenameGoal >::value();
  }
  static const char* value(const ::api_msgs::RenameGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::RenameGoalResponse> should match 
// service_traits::MD5Sum< ::api_msgs::RenameGoal > 
template<>
struct MD5Sum< ::api_msgs::RenameGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::RenameGoal >::value();
  }
  static const char* value(const ::api_msgs::RenameGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::RenameGoalResponse> should match 
// service_traits::DataType< ::api_msgs::RenameGoal > 
template<>
struct DataType< ::api_msgs::RenameGoalResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::RenameGoal >::value();
  }
  static const char* value(const ::api_msgs::RenameGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_RENAMEGOAL_H
