// Generated by gencpp from file api_msgs/SaveModifiedMapRequest.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_SAVEMODIFIEDMAPREQUEST_H
#define API_MSGS_MESSAGE_SAVEMODIFIEDMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace api_msgs
{
template <class ContainerAllocator>
struct SaveModifiedMapRequest_
{
  typedef SaveModifiedMapRequest_<ContainerAllocator> Type;

  SaveModifiedMapRequest_()
    : name()
    , base64Data()  {
    }
  SaveModifiedMapRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , base64Data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _base64Data_type;
  _base64Data_type base64Data;




  typedef boost::shared_ptr< ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveModifiedMapRequest_

typedef ::api_msgs::SaveModifiedMapRequest_<std::allocator<void> > SaveModifiedMapRequest;

typedef boost::shared_ptr< ::api_msgs::SaveModifiedMapRequest > SaveModifiedMapRequestPtr;
typedef boost::shared_ptr< ::api_msgs::SaveModifiedMapRequest const> SaveModifiedMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace api_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'api_msgs': ['/home/whj/catkin_ws/src/api/api_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3b8fcc17d528f63514c9e941caba5ee";
  }

  static const char* value(const ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3b8fcc17d528f63ULL;
  static const uint64_t static_value2 = 0x514c9e941caba5eeULL;
};

template<class ContainerAllocator>
struct DataType< ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "api_msgs/SaveModifiedMapRequest";
  }

  static const char* value(const ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
string base64Data\n\
";
  }

  static const char* value(const ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.base64Data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveModifiedMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::api_msgs::SaveModifiedMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "base64Data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.base64Data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // API_MSGS_MESSAGE_SAVEMODIFIEDMAPREQUEST_H
