// Generated by gencpp from file api_msgs/SaveModifiedMap.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_SAVEMODIFIEDMAP_H
#define API_MSGS_MESSAGE_SAVEMODIFIEDMAP_H

#include <ros/service_traits.h>


#include <api_msgs/SaveModifiedMapRequest.h>
#include <api_msgs/SaveModifiedMapResponse.h>


namespace api_msgs
{

struct SaveModifiedMap
{

typedef SaveModifiedMapRequest Request;
typedef SaveModifiedMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveModifiedMap
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::SaveModifiedMap > {
  static const char* value()
  {
    return "9bd95980b28029c6ed87bd62c7ac93f1";
  }

  static const char* value(const ::api_msgs::SaveModifiedMap&) { return value(); }
};

template<>
struct DataType< ::api_msgs::SaveModifiedMap > {
  static const char* value()
  {
    return "api_msgs/SaveModifiedMap";
  }

  static const char* value(const ::api_msgs::SaveModifiedMap&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::SaveModifiedMapRequest> should match 
// service_traits::MD5Sum< ::api_msgs::SaveModifiedMap > 
template<>
struct MD5Sum< ::api_msgs::SaveModifiedMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::SaveModifiedMap >::value();
  }
  static const char* value(const ::api_msgs::SaveModifiedMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::SaveModifiedMapRequest> should match 
// service_traits::DataType< ::api_msgs::SaveModifiedMap > 
template<>
struct DataType< ::api_msgs::SaveModifiedMapRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::SaveModifiedMap >::value();
  }
  static const char* value(const ::api_msgs::SaveModifiedMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::SaveModifiedMapResponse> should match 
// service_traits::MD5Sum< ::api_msgs::SaveModifiedMap > 
template<>
struct MD5Sum< ::api_msgs::SaveModifiedMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::SaveModifiedMap >::value();
  }
  static const char* value(const ::api_msgs::SaveModifiedMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::SaveModifiedMapResponse> should match 
// service_traits::DataType< ::api_msgs::SaveModifiedMap > 
template<>
struct DataType< ::api_msgs::SaveModifiedMapResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::SaveModifiedMap >::value();
  }
  static const char* value(const ::api_msgs::SaveModifiedMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_SAVEMODIFIEDMAP_H
