// Generated by gencpp from file api_msgs/SetInitialPose.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_SETINITIALPOSE_H
#define API_MSGS_MESSAGE_SETINITIALPOSE_H

#include <ros/service_traits.h>


#include <api_msgs/SetInitialPoseRequest.h>
#include <api_msgs/SetInitialPoseResponse.h>


namespace api_msgs
{

struct SetInitialPose
{

typedef SetInitialPoseRequest Request;
typedef SetInitialPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInitialPose
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::SetInitialPose > {
  static const char* value()
  {
    return "b6a325da20ef37edfcee672b352f2968";
  }

  static const char* value(const ::api_msgs::SetInitialPose&) { return value(); }
};

template<>
struct DataType< ::api_msgs::SetInitialPose > {
  static const char* value()
  {
    return "api_msgs/SetInitialPose";
  }

  static const char* value(const ::api_msgs::SetInitialPose&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::SetInitialPoseRequest> should match 
// service_traits::MD5Sum< ::api_msgs::SetInitialPose > 
template<>
struct MD5Sum< ::api_msgs::SetInitialPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::SetInitialPose >::value();
  }
  static const char* value(const ::api_msgs::SetInitialPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::SetInitialPoseRequest> should match 
// service_traits::DataType< ::api_msgs::SetInitialPose > 
template<>
struct DataType< ::api_msgs::SetInitialPoseRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::SetInitialPose >::value();
  }
  static const char* value(const ::api_msgs::SetInitialPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::SetInitialPoseResponse> should match 
// service_traits::MD5Sum< ::api_msgs::SetInitialPose > 
template<>
struct MD5Sum< ::api_msgs::SetInitialPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::SetInitialPose >::value();
  }
  static const char* value(const ::api_msgs::SetInitialPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::SetInitialPoseResponse> should match 
// service_traits::DataType< ::api_msgs::SetInitialPose > 
template<>
struct DataType< ::api_msgs::SetInitialPoseResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::SetInitialPose >::value();
  }
  static const char* value(const ::api_msgs::SetInitialPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_SETINITIALPOSE_H
