// Generated by gencpp from file api_msgs/UploadMapRequest.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_UPLOADMAPREQUEST_H
#define API_MSGS_MESSAGE_UPLOADMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace api_msgs
{
template <class ContainerAllocator>
struct UploadMapRequest_
{
  typedef UploadMapRequest_<ContainerAllocator> Type;

  UploadMapRequest_()
    : name()
    , mapData()
    , yamlData()  {
    }
  UploadMapRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , mapData(_alloc)
    , yamlData(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mapData_type;
  _mapData_type mapData;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _yamlData_type;
  _yamlData_type yamlData;




  typedef boost::shared_ptr< ::api_msgs::UploadMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::api_msgs::UploadMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UploadMapRequest_

typedef ::api_msgs::UploadMapRequest_<std::allocator<void> > UploadMapRequest;

typedef boost::shared_ptr< ::api_msgs::UploadMapRequest > UploadMapRequestPtr;
typedef boost::shared_ptr< ::api_msgs::UploadMapRequest const> UploadMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::api_msgs::UploadMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::api_msgs::UploadMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace api_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'api_msgs': ['/home/whj/catkin_ws/src/api/api_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::api_msgs::UploadMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api_msgs::UploadMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api_msgs::UploadMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api_msgs::UploadMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api_msgs::UploadMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api_msgs::UploadMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::api_msgs::UploadMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6890f2dbbc8ff8b95bc80b4604289feb";
  }

  static const char* value(const ::api_msgs::UploadMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6890f2dbbc8ff8b9ULL;
  static const uint64_t static_value2 = 0x5bc80b4604289febULL;
};

template<class ContainerAllocator>
struct DataType< ::api_msgs::UploadMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "api_msgs/UploadMapRequest";
  }

  static const char* value(const ::api_msgs::UploadMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::api_msgs::UploadMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
string mapData\n\
string yamlData\n\
";
  }

  static const char* value(const ::api_msgs::UploadMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::api_msgs::UploadMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.mapData);
      stream.next(m.yamlData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UploadMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::api_msgs::UploadMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::api_msgs::UploadMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "mapData: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mapData);
    s << indent << "yamlData: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.yamlData);
  }
};

} // namespace message_operations
} // namespace ros

#endif // API_MSGS_MESSAGE_UPLOADMAPREQUEST_H
