// Generated by gencpp from file api_msgs/UploadMap.msg
// DO NOT EDIT!


#ifndef API_MSGS_MESSAGE_UPLOADMAP_H
#define API_MSGS_MESSAGE_UPLOADMAP_H

#include <ros/service_traits.h>


#include <api_msgs/UploadMapRequest.h>
#include <api_msgs/UploadMapResponse.h>


namespace api_msgs
{

struct UploadMap
{

typedef UploadMapRequest Request;
typedef UploadMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UploadMap
} // namespace api_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api_msgs::UploadMap > {
  static const char* value()
  {
    return "cfd78f574ce6584df58e90daeaf81197";
  }

  static const char* value(const ::api_msgs::UploadMap&) { return value(); }
};

template<>
struct DataType< ::api_msgs::UploadMap > {
  static const char* value()
  {
    return "api_msgs/UploadMap";
  }

  static const char* value(const ::api_msgs::UploadMap&) { return value(); }
};


// service_traits::MD5Sum< ::api_msgs::UploadMapRequest> should match 
// service_traits::MD5Sum< ::api_msgs::UploadMap > 
template<>
struct MD5Sum< ::api_msgs::UploadMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::UploadMap >::value();
  }
  static const char* value(const ::api_msgs::UploadMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::UploadMapRequest> should match 
// service_traits::DataType< ::api_msgs::UploadMap > 
template<>
struct DataType< ::api_msgs::UploadMapRequest>
{
  static const char* value()
  {
    return DataType< ::api_msgs::UploadMap >::value();
  }
  static const char* value(const ::api_msgs::UploadMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api_msgs::UploadMapResponse> should match 
// service_traits::MD5Sum< ::api_msgs::UploadMap > 
template<>
struct MD5Sum< ::api_msgs::UploadMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api_msgs::UploadMap >::value();
  }
  static const char* value(const ::api_msgs::UploadMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api_msgs::UploadMapResponse> should match 
// service_traits::DataType< ::api_msgs::UploadMap > 
template<>
struct DataType< ::api_msgs::UploadMapResponse>
{
  static const char* value()
  {
    return DataType< ::api_msgs::UploadMap >::value();
  }
  static const char* value(const ::api_msgs::UploadMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MSGS_MESSAGE_UPLOADMAP_H
