// Generated by gencpp from file api/AddGoal.msg
// DO NOT EDIT!


#ifndef API_MESSAGE_ADDGOAL_H
#define API_MESSAGE_ADDGOAL_H

#include <ros/service_traits.h>


#include <api/AddGoalRequest.h>
#include <api/AddGoalResponse.h>


namespace api
{

struct AddGoal
{

typedef AddGoalRequest Request;
typedef AddGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddGoal
} // namespace api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api::AddGoal > {
  static const char* value()
  {
    return "802c28d41326fad853e80597ef4c8c7f";
  }

  static const char* value(const ::api::AddGoal&) { return value(); }
};

template<>
struct DataType< ::api::AddGoal > {
  static const char* value()
  {
    return "api/AddGoal";
  }

  static const char* value(const ::api::AddGoal&) { return value(); }
};


// service_traits::MD5Sum< ::api::AddGoalRequest> should match 
// service_traits::MD5Sum< ::api::AddGoal > 
template<>
struct MD5Sum< ::api::AddGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api::AddGoal >::value();
  }
  static const char* value(const ::api::AddGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api::AddGoalRequest> should match 
// service_traits::DataType< ::api::AddGoal > 
template<>
struct DataType< ::api::AddGoalRequest>
{
  static const char* value()
  {
    return DataType< ::api::AddGoal >::value();
  }
  static const char* value(const ::api::AddGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api::AddGoalResponse> should match 
// service_traits::MD5Sum< ::api::AddGoal > 
template<>
struct MD5Sum< ::api::AddGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api::AddGoal >::value();
  }
  static const char* value(const ::api::AddGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api::AddGoalResponse> should match 
// service_traits::DataType< ::api::AddGoal > 
template<>
struct DataType< ::api::AddGoalResponse>
{
  static const char* value()
  {
    return DataType< ::api::AddGoal >::value();
  }
  static const char* value(const ::api::AddGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MESSAGE_ADDGOAL_H
