// Generated by gencpp from file api/DelGoal.msg
// DO NOT EDIT!


#ifndef API_MESSAGE_DELGOAL_H
#define API_MESSAGE_DELGOAL_H

#include <ros/service_traits.h>


#include <api/DelGoalRequest.h>
#include <api/DelGoalResponse.h>


namespace api
{

struct DelGoal
{

typedef DelGoalRequest Request;
typedef DelGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DelGoal
} // namespace api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api::DelGoal > {
  static const char* value()
  {
    return "802c28d41326fad853e80597ef4c8c7f";
  }

  static const char* value(const ::api::DelGoal&) { return value(); }
};

template<>
struct DataType< ::api::DelGoal > {
  static const char* value()
  {
    return "api/DelGoal";
  }

  static const char* value(const ::api::DelGoal&) { return value(); }
};


// service_traits::MD5Sum< ::api::DelGoalRequest> should match 
// service_traits::MD5Sum< ::api::DelGoal > 
template<>
struct MD5Sum< ::api::DelGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api::DelGoal >::value();
  }
  static const char* value(const ::api::DelGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api::DelGoalRequest> should match 
// service_traits::DataType< ::api::DelGoal > 
template<>
struct DataType< ::api::DelGoalRequest>
{
  static const char* value()
  {
    return DataType< ::api::DelGoal >::value();
  }
  static const char* value(const ::api::DelGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api::DelGoalResponse> should match 
// service_traits::MD5Sum< ::api::DelGoal > 
template<>
struct MD5Sum< ::api::DelGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api::DelGoal >::value();
  }
  static const char* value(const ::api::DelGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api::DelGoalResponse> should match 
// service_traits::DataType< ::api::DelGoal > 
template<>
struct DataType< ::api::DelGoalResponse>
{
  static const char* value()
  {
    return DataType< ::api::DelGoal >::value();
  }
  static const char* value(const ::api::DelGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MESSAGE_DELGOAL_H
