// Generated by gencpp from file api/GoalList.msg
// DO NOT EDIT!


#ifndef API_MESSAGE_GOALLIST_H
#define API_MESSAGE_GOALLIST_H

#include <ros/service_traits.h>


#include <api/GoalListRequest.h>
#include <api/GoalListResponse.h>


namespace api
{

struct GoalList
{

typedef GoalListRequest Request;
typedef GoalListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoalList
} // namespace api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api::GoalList > {
  static const char* value()
  {
    return "6ded0e823bc3364a8e51670166f50c09";
  }

  static const char* value(const ::api::GoalList&) { return value(); }
};

template<>
struct DataType< ::api::GoalList > {
  static const char* value()
  {
    return "api/GoalList";
  }

  static const char* value(const ::api::GoalList&) { return value(); }
};


// service_traits::MD5Sum< ::api::GoalListRequest> should match 
// service_traits::MD5Sum< ::api::GoalList > 
template<>
struct MD5Sum< ::api::GoalListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api::GoalList >::value();
  }
  static const char* value(const ::api::GoalListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api::GoalListRequest> should match 
// service_traits::DataType< ::api::GoalList > 
template<>
struct DataType< ::api::GoalListRequest>
{
  static const char* value()
  {
    return DataType< ::api::GoalList >::value();
  }
  static const char* value(const ::api::GoalListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api::GoalListResponse> should match 
// service_traits::MD5Sum< ::api::GoalList > 
template<>
struct MD5Sum< ::api::GoalListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api::GoalList >::value();
  }
  static const char* value(const ::api::GoalListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api::GoalListResponse> should match 
// service_traits::DataType< ::api::GoalList > 
template<>
struct DataType< ::api::GoalListResponse>
{
  static const char* value()
  {
    return DataType< ::api::GoalList >::value();
  }
  static const char* value(const ::api::GoalListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MESSAGE_GOALLIST_H
