// Generated by gencpp from file api/GoalListResponse.msg
// DO NOT EDIT!


#ifndef API_MESSAGE_GOALLISTRESPONSE_H
#define API_MESSAGE_GOALLISTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace api
{
template <class ContainerAllocator>
struct GoalListResponse_
{
  typedef GoalListResponse_<ContainerAllocator> Type;

  GoalListResponse_()
    : goalList()  {
    }
  GoalListResponse_(const ContainerAllocator& _alloc)
    : goalList(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _goalList_type;
  _goalList_type goalList;




  typedef boost::shared_ptr< ::api::GoalListResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::api::GoalListResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GoalListResponse_

typedef ::api::GoalListResponse_<std::allocator<void> > GoalListResponse;

typedef boost::shared_ptr< ::api::GoalListResponse > GoalListResponsePtr;
typedef boost::shared_ptr< ::api::GoalListResponse const> GoalListResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::api::GoalListResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::api::GoalListResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace api

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'api': ['/home/whj/catkin_ws/src/api/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::api::GoalListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api::GoalListResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api::GoalListResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api::GoalListResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api::GoalListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api::GoalListResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::api::GoalListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc37a6c620124f14e8cc5f76efaf8a76";
  }

  static const char* value(const ::api::GoalListResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc37a6c620124f14ULL;
  static const uint64_t static_value2 = 0xe8cc5f76efaf8a76ULL;
};

template<class ContainerAllocator>
struct DataType< ::api::GoalListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "api/GoalListResponse";
  }

  static const char* value(const ::api::GoalListResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::api::GoalListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string goalList\n\
\n\
";
  }

  static const char* value(const ::api::GoalListResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::api::GoalListResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goalList);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalListResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::api::GoalListResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::api::GoalListResponse_<ContainerAllocator>& v)
  {
    s << indent << "goalList: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.goalList);
  }
};

} // namespace message_operations
} // namespace ros

#endif // API_MESSAGE_GOALLISTRESPONSE_H
