// Generated by gencpp from file api/GridLaser.msg
// DO NOT EDIT!


#ifndef API_MESSAGE_GRIDLASER_H
#define API_MESSAGE_GRIDLASER_H

#include <ros/service_traits.h>


#include <api/GridLaserRequest.h>
#include <api/GridLaserResponse.h>


namespace api
{

struct GridLaser
{

typedef GridLaserRequest Request;
typedef GridLaserResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GridLaser
} // namespace api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api::GridLaser > {
  static const char* value()
  {
    return "70385a002e518c7e14ab0566622593e3";
  }

  static const char* value(const ::api::GridLaser&) { return value(); }
};

template<>
struct DataType< ::api::GridLaser > {
  static const char* value()
  {
    return "api/GridLaser";
  }

  static const char* value(const ::api::GridLaser&) { return value(); }
};


// service_traits::MD5Sum< ::api::GridLaserRequest> should match 
// service_traits::MD5Sum< ::api::GridLaser > 
template<>
struct MD5Sum< ::api::GridLaserRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api::GridLaser >::value();
  }
  static const char* value(const ::api::GridLaserRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api::GridLaserRequest> should match 
// service_traits::DataType< ::api::GridLaser > 
template<>
struct DataType< ::api::GridLaserRequest>
{
  static const char* value()
  {
    return DataType< ::api::GridLaser >::value();
  }
  static const char* value(const ::api::GridLaserRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api::GridLaserResponse> should match 
// service_traits::MD5Sum< ::api::GridLaser > 
template<>
struct MD5Sum< ::api::GridLaserResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api::GridLaser >::value();
  }
  static const char* value(const ::api::GridLaserResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api::GridLaserResponse> should match 
// service_traits::DataType< ::api::GridLaser > 
template<>
struct DataType< ::api::GridLaserResponse>
{
  static const char* value()
  {
    return DataType< ::api::GridLaser >::value();
  }
  static const char* value(const ::api::GridLaserResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MESSAGE_GRIDLASER_H
