// Generated by gencpp from file api/GridLaserResponse.msg
// DO NOT EDIT!


#ifndef API_MESSAGE_GRIDLASERRESPONSE_H
#define API_MESSAGE_GRIDLASERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <api/GridPoint.h>

namespace api
{
template <class ContainerAllocator>
struct GridLaserResponse_
{
  typedef GridLaserResponse_<ContainerAllocator> Type;

  GridLaserResponse_()
    : laserPoint()
    , mapGridWidth(0)
    , mapGridHeight(0)
    , mapResolution(0.0)
    , msg()  {
    }
  GridLaserResponse_(const ContainerAllocator& _alloc)
    : laserPoint(_alloc)
    , mapGridWidth(0)
    , mapGridHeight(0)
    , mapResolution(0.0)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::api::GridPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::api::GridPoint_<ContainerAllocator> >::other >  _laserPoint_type;
  _laserPoint_type laserPoint;

   typedef int32_t _mapGridWidth_type;
  _mapGridWidth_type mapGridWidth;

   typedef int32_t _mapGridHeight_type;
  _mapGridHeight_type mapGridHeight;

   typedef float _mapResolution_type;
  _mapResolution_type mapResolution;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;




  typedef boost::shared_ptr< ::api::GridLaserResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::api::GridLaserResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GridLaserResponse_

typedef ::api::GridLaserResponse_<std::allocator<void> > GridLaserResponse;

typedef boost::shared_ptr< ::api::GridLaserResponse > GridLaserResponsePtr;
typedef boost::shared_ptr< ::api::GridLaserResponse const> GridLaserResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::api::GridLaserResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::api::GridLaserResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace api

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'api': ['/home/whj/catkin_ws/src/api/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::api::GridLaserResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api::GridLaserResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api::GridLaserResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api::GridLaserResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api::GridLaserResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api::GridLaserResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::api::GridLaserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fae0bf771ee3824e3c4d670821bd5e83";
  }

  static const char* value(const ::api::GridLaserResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfae0bf771ee3824eULL;
  static const uint64_t static_value2 = 0x3c4d670821bd5e83ULL;
};

template<class ContainerAllocator>
struct DataType< ::api::GridLaserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "api/GridLaserResponse";
  }

  static const char* value(const ::api::GridLaserResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::api::GridLaserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "GridPoint[] laserPoint\n\
int32 mapGridWidth\n\
int32 mapGridHeight\n\
float32 mapResolution\n\
string msg\n\
\n\
\n\
================================================================================\n\
MSG: api/GridPoint\n\
int32 x\n\
int32 y\n\
";
  }

  static const char* value(const ::api::GridLaserResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::api::GridLaserResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.laserPoint);
      stream.next(m.mapGridWidth);
      stream.next(m.mapGridHeight);
      stream.next(m.mapResolution);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GridLaserResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::api::GridLaserResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::api::GridLaserResponse_<ContainerAllocator>& v)
  {
    s << indent << "laserPoint[]" << std::endl;
    for (size_t i = 0; i < v.laserPoint.size(); ++i)
    {
      s << indent << "  laserPoint[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::api::GridPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.laserPoint[i]);
    }
    s << indent << "mapGridWidth: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mapGridWidth);
    s << indent << "mapGridHeight: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mapGridHeight);
    s << indent << "mapResolution: ";
    Printer<float>::stream(s, indent + "  ", v.mapResolution);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // API_MESSAGE_GRIDLASERRESPONSE_H
