// Generated by gencpp from file api/MapList.msg
// DO NOT EDIT!


#ifndef API_MESSAGE_MAPLIST_H
#define API_MESSAGE_MAPLIST_H

#include <ros/service_traits.h>


#include <api/MapListRequest.h>
#include <api/MapListResponse.h>


namespace api
{

struct MapList
{

typedef MapListRequest Request;
typedef MapListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapList
} // namespace api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api::MapList > {
  static const char* value()
  {
    return "68d5e7574159c309cadccc1b40fe9cc1";
  }

  static const char* value(const ::api::MapList&) { return value(); }
};

template<>
struct DataType< ::api::MapList > {
  static const char* value()
  {
    return "api/MapList";
  }

  static const char* value(const ::api::MapList&) { return value(); }
};


// service_traits::MD5Sum< ::api::MapListRequest> should match 
// service_traits::MD5Sum< ::api::MapList > 
template<>
struct MD5Sum< ::api::MapListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api::MapList >::value();
  }
  static const char* value(const ::api::MapListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api::MapListRequest> should match 
// service_traits::DataType< ::api::MapList > 
template<>
struct DataType< ::api::MapListRequest>
{
  static const char* value()
  {
    return DataType< ::api::MapList >::value();
  }
  static const char* value(const ::api::MapListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api::MapListResponse> should match 
// service_traits::MD5Sum< ::api::MapList > 
template<>
struct MD5Sum< ::api::MapListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api::MapList >::value();
  }
  static const char* value(const ::api::MapListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api::MapListResponse> should match 
// service_traits::DataType< ::api::MapList > 
template<>
struct DataType< ::api::MapListResponse>
{
  static const char* value()
  {
    return DataType< ::api::MapList >::value();
  }
  static const char* value(const ::api::MapListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MESSAGE_MAPLIST_H
