// Generated by gencpp from file api/MapRenameRequest.msg
// DO NOT EDIT!


#ifndef API_MESSAGE_MAPRENAMEREQUEST_H
#define API_MESSAGE_MAPRENAMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace api
{
template <class ContainerAllocator>
struct MapRenameRequest_
{
  typedef MapRenameRequest_<ContainerAllocator> Type;

  MapRenameRequest_()
    : oldName()  {
    }
  MapRenameRequest_(const ContainerAllocator& _alloc)
    : oldName(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _oldName_type;
  _oldName_type oldName;




  typedef boost::shared_ptr< ::api::MapRenameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::api::MapRenameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MapRenameRequest_

typedef ::api::MapRenameRequest_<std::allocator<void> > MapRenameRequest;

typedef boost::shared_ptr< ::api::MapRenameRequest > MapRenameRequestPtr;
typedef boost::shared_ptr< ::api::MapRenameRequest const> MapRenameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::api::MapRenameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::api::MapRenameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace api

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'api': ['/home/whj/catkin_ws/src/api/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::api::MapRenameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::api::MapRenameRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api::MapRenameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::api::MapRenameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api::MapRenameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::api::MapRenameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::api::MapRenameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f752c78c5674772939c05f88a338b459";
  }

  static const char* value(const ::api::MapRenameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf752c78c56747729ULL;
  static const uint64_t static_value2 = 0x39c05f88a338b459ULL;
};

template<class ContainerAllocator>
struct DataType< ::api::MapRenameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "api/MapRenameRequest";
  }

  static const char* value(const ::api::MapRenameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::api::MapRenameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string oldName\n\
";
  }

  static const char* value(const ::api::MapRenameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::api::MapRenameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.oldName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapRenameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::api::MapRenameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::api::MapRenameRequest_<ContainerAllocator>& v)
  {
    s << indent << "oldName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.oldName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // API_MESSAGE_MAPRENAMEREQUEST_H
