// Generated by gencpp from file api/MapRename.msg
// DO NOT EDIT!


#ifndef API_MESSAGE_MAPRENAME_H
#define API_MESSAGE_MAPRENAME_H

#include <ros/service_traits.h>


#include <api/MapRenameRequest.h>
#include <api/MapRenameResponse.h>


namespace api
{

struct MapRename
{

typedef MapRenameRequest Request;
typedef MapRenameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapRename
} // namespace api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api::MapRename > {
  static const char* value()
  {
    return "12d2a39948ea8253e5f441c3a0f822dc";
  }

  static const char* value(const ::api::MapRename&) { return value(); }
};

template<>
struct DataType< ::api::MapRename > {
  static const char* value()
  {
    return "api/MapRename";
  }

  static const char* value(const ::api::MapRename&) { return value(); }
};


// service_traits::MD5Sum< ::api::MapRenameRequest> should match 
// service_traits::MD5Sum< ::api::MapRename > 
template<>
struct MD5Sum< ::api::MapRenameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api::MapRename >::value();
  }
  static const char* value(const ::api::MapRenameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api::MapRenameRequest> should match 
// service_traits::DataType< ::api::MapRename > 
template<>
struct DataType< ::api::MapRenameRequest>
{
  static const char* value()
  {
    return DataType< ::api::MapRename >::value();
  }
  static const char* value(const ::api::MapRenameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api::MapRenameResponse> should match 
// service_traits::MD5Sum< ::api::MapRename > 
template<>
struct MD5Sum< ::api::MapRenameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api::MapRename >::value();
  }
  static const char* value(const ::api::MapRenameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api::MapRenameResponse> should match 
// service_traits::DataType< ::api::MapRename > 
template<>
struct DataType< ::api::MapRenameResponse>
{
  static const char* value()
  {
    return DataType< ::api::MapRename >::value();
  }
  static const char* value(const ::api::MapRenameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MESSAGE_MAPRENAME_H
