// Generated by gencpp from file api/SetGoal.msg
// DO NOT EDIT!


#ifndef API_MESSAGE_SETGOAL_H
#define API_MESSAGE_SETGOAL_H

#include <ros/service_traits.h>


#include <api/SetGoalRequest.h>
#include <api/SetGoalResponse.h>


namespace api
{

struct SetGoal
{

typedef SetGoalRequest Request;
typedef SetGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGoal
} // namespace api


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::api::SetGoal > {
  static const char* value()
  {
    return "444061e7bc06ee0199b2220d81ce3a4a";
  }

  static const char* value(const ::api::SetGoal&) { return value(); }
};

template<>
struct DataType< ::api::SetGoal > {
  static const char* value()
  {
    return "api/SetGoal";
  }

  static const char* value(const ::api::SetGoal&) { return value(); }
};


// service_traits::MD5Sum< ::api::SetGoalRequest> should match 
// service_traits::MD5Sum< ::api::SetGoal > 
template<>
struct MD5Sum< ::api::SetGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::api::SetGoal >::value();
  }
  static const char* value(const ::api::SetGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::api::SetGoalRequest> should match 
// service_traits::DataType< ::api::SetGoal > 
template<>
struct DataType< ::api::SetGoalRequest>
{
  static const char* value()
  {
    return DataType< ::api::SetGoal >::value();
  }
  static const char* value(const ::api::SetGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::api::SetGoalResponse> should match 
// service_traits::MD5Sum< ::api::SetGoal > 
template<>
struct MD5Sum< ::api::SetGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::api::SetGoal >::value();
  }
  static const char* value(const ::api::SetGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::api::SetGoalResponse> should match 
// service_traits::DataType< ::api::SetGoal > 
template<>
struct DataType< ::api::SetGoalResponse>
{
  static const char* value()
  {
    return DataType< ::api::SetGoal >::value();
  }
  static const char* value(const ::api::SetGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // API_MESSAGE_SETGOAL_H
