// Generated by gencpp from file my_tutorial/GoalList.msg
// DO NOT EDIT!


#ifndef MY_TUTORIAL_MESSAGE_GOALLIST_H
#define MY_TUTORIAL_MESSAGE_GOALLIST_H

#include <ros/service_traits.h>


#include <my_tutorial/GoalListRequest.h>
#include <my_tutorial/GoalListResponse.h>


namespace my_tutorial
{

struct GoalList
{

typedef GoalListRequest Request;
typedef GoalListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoalList
} // namespace my_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_tutorial::GoalList > {
  static const char* value()
  {
    return "6ded0e823bc3364a8e51670166f50c09";
  }

  static const char* value(const ::my_tutorial::GoalList&) { return value(); }
};

template<>
struct DataType< ::my_tutorial::GoalList > {
  static const char* value()
  {
    return "my_tutorial/GoalList";
  }

  static const char* value(const ::my_tutorial::GoalList&) { return value(); }
};


// service_traits::MD5Sum< ::my_tutorial::GoalListRequest> should match 
// service_traits::MD5Sum< ::my_tutorial::GoalList > 
template<>
struct MD5Sum< ::my_tutorial::GoalListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_tutorial::GoalList >::value();
  }
  static const char* value(const ::my_tutorial::GoalListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_tutorial::GoalListRequest> should match 
// service_traits::DataType< ::my_tutorial::GoalList > 
template<>
struct DataType< ::my_tutorial::GoalListRequest>
{
  static const char* value()
  {
    return DataType< ::my_tutorial::GoalList >::value();
  }
  static const char* value(const ::my_tutorial::GoalListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_tutorial::GoalListResponse> should match 
// service_traits::MD5Sum< ::my_tutorial::GoalList > 
template<>
struct MD5Sum< ::my_tutorial::GoalListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_tutorial::GoalList >::value();
  }
  static const char* value(const ::my_tutorial::GoalListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_tutorial::GoalListResponse> should match 
// service_traits::DataType< ::my_tutorial::GoalList > 
template<>
struct DataType< ::my_tutorial::GoalListResponse>
{
  static const char* value()
  {
    return DataType< ::my_tutorial::GoalList >::value();
  }
  static const char* value(const ::my_tutorial::GoalListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_TUTORIAL_MESSAGE_GOALLIST_H
