// Generated by gencpp from file my_tutorial/GridGoalRequest.msg
// DO NOT EDIT!


#ifndef MY_TUTORIAL_MESSAGE_GRIDGOALREQUEST_H
#define MY_TUTORIAL_MESSAGE_GRIDGOALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_tutorial/GridPose.h>

namespace my_tutorial
{
template <class ContainerAllocator>
struct GridGoalRequest_
{
  typedef GridGoalRequest_<ContainerAllocator> Type;

  GridGoalRequest_()
    : goal()  {
    }
  GridGoalRequest_(const ContainerAllocator& _alloc)
    : goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::my_tutorial::GridPose_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::my_tutorial::GridGoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_tutorial::GridGoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GridGoalRequest_

typedef ::my_tutorial::GridGoalRequest_<std::allocator<void> > GridGoalRequest;

typedef boost::shared_ptr< ::my_tutorial::GridGoalRequest > GridGoalRequestPtr;
typedef boost::shared_ptr< ::my_tutorial::GridGoalRequest const> GridGoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_tutorial::GridGoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_tutorial::GridGoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'my_tutorial': ['/home/whj/catkin_ws/src/my_tutorial/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_tutorial::GridGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_tutorial::GridGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_tutorial::GridGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_tutorial::GridGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_tutorial::GridGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_tutorial::GridGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_tutorial::GridGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cdbe27f4e4d83abd1ed8bb4f3ca9f9f1";
  }

  static const char* value(const ::my_tutorial::GridGoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcdbe27f4e4d83abdULL;
  static const uint64_t static_value2 = 0x1ed8bb4f3ca9f9f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_tutorial::GridGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_tutorial/GridGoalRequest";
  }

  static const char* value(const ::my_tutorial::GridGoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_tutorial::GridGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_tutorial/GridPose goal\n\
\n\
================================================================================\n\
MSG: my_tutorial/GridPose\n\
float32   angle\n\
int32   grid_x\n\
int32   grid_y\n\
";
  }

  static const char* value(const ::my_tutorial::GridGoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_tutorial::GridGoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GridGoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_tutorial::GridGoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_tutorial::GridGoalRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::my_tutorial::GridPose_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_TUTORIAL_MESSAGE_GRIDGOALREQUEST_H
