// Generated by gencpp from file my_tutorial/MapData.msg
// DO NOT EDIT!


#ifndef MY_TUTORIAL_MESSAGE_MAPDATA_H
#define MY_TUTORIAL_MESSAGE_MAPDATA_H

#include <ros/service_traits.h>


#include <my_tutorial/MapDataRequest.h>
#include <my_tutorial/MapDataResponse.h>


namespace my_tutorial
{

struct MapData
{

typedef MapDataRequest Request;
typedef MapDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapData
} // namespace my_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_tutorial::MapData > {
  static const char* value()
  {
    return "7aab8e6323541cb09b49f080c6bbdaf3";
  }

  static const char* value(const ::my_tutorial::MapData&) { return value(); }
};

template<>
struct DataType< ::my_tutorial::MapData > {
  static const char* value()
  {
    return "my_tutorial/MapData";
  }

  static const char* value(const ::my_tutorial::MapData&) { return value(); }
};


// service_traits::MD5Sum< ::my_tutorial::MapDataRequest> should match 
// service_traits::MD5Sum< ::my_tutorial::MapData > 
template<>
struct MD5Sum< ::my_tutorial::MapDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_tutorial::MapData >::value();
  }
  static const char* value(const ::my_tutorial::MapDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_tutorial::MapDataRequest> should match 
// service_traits::DataType< ::my_tutorial::MapData > 
template<>
struct DataType< ::my_tutorial::MapDataRequest>
{
  static const char* value()
  {
    return DataType< ::my_tutorial::MapData >::value();
  }
  static const char* value(const ::my_tutorial::MapDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_tutorial::MapDataResponse> should match 
// service_traits::MD5Sum< ::my_tutorial::MapData > 
template<>
struct MD5Sum< ::my_tutorial::MapDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_tutorial::MapData >::value();
  }
  static const char* value(const ::my_tutorial::MapDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_tutorial::MapDataResponse> should match 
// service_traits::DataType< ::my_tutorial::MapData > 
template<>
struct DataType< ::my_tutorial::MapDataResponse>
{
  static const char* value()
  {
    return DataType< ::my_tutorial::MapData >::value();
  }
  static const char* value(const ::my_tutorial::MapDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_TUTORIAL_MESSAGE_MAPDATA_H
